version: '3'

services:
  nginx:
    container_name: nginx_webserver
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/