version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/ngnix/conf.d/default.conf

  php:
    container_name: php
    image: php:8.1
    restart: always
    volumes:
      - "/data/ptsp:/var/www/html"
  
  database:
    container_name: mysql
    image: mysql:8.1
    restart: always
    ports:
    - 3306:3306
    environment:
      - MYSQL_DATABASE=ptsp
      - MYSQL_USER=ptsp
      - MYSQL_PASSWORD=706Jakarta
      - MYSQL_ROOT_PASSWORD=706Jakarta

