version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/ngnix/conf.d/default.conf

  database:
    container_name: mysql
    image: mysql:8.1
    restart: always
    ports:
    - 3306:3306
    environment:
      - MYSQL_DATABASE=ptsp
      - MYSQL_USER=ptsp
      - MYSQL_PASSWORD=706Jakarta
      - MYSQL_ROOT_PASSWORD=706Jakarta

  ptsp:
    image: ptsp
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 81:80
    volumes:
      - "/data/ptsp:/var/www/html"
    restart: unless-stopped